"""initial schema

Revision ID: e5250214df58
Revises: 
Create Date: 2026-07-24 18:05:08.765950

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = 'e5250214df58'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('authors', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('original_title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_year_text', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('edition_statement', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('physical_description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editions_isbn'), 'editions', ['isbn'], unique=False)
    op.create_table('copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('inventory_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_source', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('acquisition_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('storage_location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_autograph', sa.Boolean(), nullable=False),
    sa.Column('has_ex_libris', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_code')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copy_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['copies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    op.drop_table('copies')
    op.drop_index(op.f('ix_editions_isbn'), table_name='editions')
    op.drop_table('editions')
    # ### end Alembic commands ###
